### ISSUE TITLE
migrate AB tests to smth compatible with depandabot

### ISSUE THREAD

**Issue by fjetter** [coiled/benchmarks#1437]
It happens rather frequently that I am running on rather old versions of dask/distributed in AB_environments. We're not doing a good job of updating those environments. I wanted to setup depandabot for this job but noticed that conda is not even supported.

I suggest to move off of conda for the A/B tests to smth else, e.g. pip / pip-compile that supports dependabot and let it update the dependencies at a regular cadence

**Comment by crusaderky** [comment]
Apologies for not noticing this ticket sooner.

I think that letting A/B tests diverge from nightly ones (`ci/environment*.yml`) would be a very bad idea.
If we want to use dependabot, we should use it everywhere so that they remain in sync.

Also, the idea behind dependabot is that it will trigger CI for you to prove that everything keeps working.
However, A/B tests do not run on a commit by default, so you may end up accepting changes without knowing if they cause a failure or not. Again this would be fixed by including the nightly environments in dependabot.

We also need to ensure that dependabot doesn't introduce performance regressions - so we should enable the `regressions` workflow for dependabot PRs only (it's currently only active for nightly runs).

Finally, I suspect that dependabot would trigger _a lot_ of extra CI runs, and it would severely add to noise if it upgrades _too_ frequently. I think we should investigate a setting to limit it to a bulk upload e.g. biweekly, instead of letting it create a new PR every time any one dependency does a minor release.
