### ISSUE TITLE
s3 throughput much higher on some workers?

### ISSUE THREAD

**Issue by crusaderky** [coiled/benchmarks#821]
![image](https://user-images.githubusercontent.com/6213168/234855554-3ef3056d-c704-4620-8196-6aec73063a27.png)

In this test,
- [s3fs] is a raw file read with fsspec from s3:// of a 562 MiB file, from a single dask task
- [pandas] is a call to pandas that reads and decodes the whole parquet dataset from a single dask task
- [dask] parallelizes the read and decode across 5 different workers (the file is chunked).

The file: `s3://coiled-runtime-ci/ookla-open-data/type=fixed/year=2022/quarter=1/2022-01-01_performance_fixed_tiles.parquet`

The data seems to indicate that, depending on which worker you land, you will get much faster or slower throughput - with up to a factor of 3x variance (8s ~ 22s).

Is this something we're already aware of? Is it to be expected?

CC @ntabris

**Comment by ntabris** [comment]
Just be clear, you're thinking about the variance across distinct runs of the same test?

**Comment by crusaderky** [comment]
@ntabris yes

**Comment by ntabris** [comment]
For the record...

@crusaderky and I had a quick chat and looked at the network throughput metrics on a few runs. The rate metrics we have aren't ideal because the test is so short, but we would still expect to see higher variance in the metrics than we see if network throughput was the primary explanation.

I told @crusaderky that my impression is that the network throughput we get on Coiled reading from s3 could be much better, and pointed him to various related issues:

- https://github.com/coiled/general/issues/154
- https://github.com/fsspec/s3fs/issues/677
- https://github.com/coiled/parquet-scaling-best-practices/issues/11

He mentioned that he might try something like `subprocess.check_call("aws s3 cp s3:// /dev/null", shell=True)` to see what the theoretical limit is, I'd also be interested in seeing that.

My impression is that we aren't opening enough concurrent connection to get good throughput, but I haven't spent a lot of time investigating.

**Comment by crusaderky** [comment]
I inspected the cluster dumps.
In a "fast" run of the [s3fs] variant, which took end-to-end 6.5s, the task was in executing state for 6.48s.
In a "slow" run, which took end-to-end 16.3s, the task was in executing state for 16.25s.
I don't have the fine performance metrics in the dumps but I don't expect them to show anything other than `thread-noncpu`.
So 99% of the runtime - and of the variance - is confirmed to be caused by these 2 lines:
https://github.com/coiled/benchmarks/blob/35cb331d66bd5b504391e293a332229dddd4e020/tests/benchmarks/test_parquet.py#L106-L108

**Comment by crusaderky** [comment]
https://github.com/coiled/benchmarks/pull/825#issuecomment-1532905248 seems to strongly indicate that there is a strong correlation between throughput and how many times the file was requested over the last few seconds. If you rerun the test over and over from multiple A/B tests, it will start slow (35 MiB/s) and then drastically speed up (87 MiB/s), as S3 shifts to something faster.
